# Generated by Django 5.2.3 on 2025-06-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicion', models.IntegerField(blank=True, null=True)),
                ('id_informante', models.IntegerField(blank=True, null=True)),
                ('id_junta', models.IntegerField(blank=True, null=True)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('provincia', models.IntegerField(blank=True, null=True)),
                ('comuna', models.IntegerField(blank=True, null=True)),
                ('utm_norte', models.FloatField(blank=True, null=True)),
                ('utm_este', models.FloatField(blank=True, null=True)),
                ('huso', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_cuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_cuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_acuifero', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_acuifero', models.CharField(blank=True, max_length=100, null=True)),
                ('sector_sha', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_subcuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_subcuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_subsubcuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_subsubcuenca', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_fuente_superficial', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_fuente_superficial', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('extrae_canal', models.BooleanField(blank=True, null=True)),
                ('nombre_canal', models.CharField(blank=True, max_length=100, null=True)),
                ('apr', models.BooleanField(blank=True, null=True)),
                ('puntoalt', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_motobomba', models.BooleanField(blank=True, null=True)),
                ('tiene_bocatoma', models.BooleanField(blank=True, null=True)),
                ('tipo_bocatoma', models.CharField(blank=True, max_length=100, null=True)),
                ('descarga_cauce_natural', models.BooleanField(blank=True, null=True)),
                ('habilitada', models.BooleanField(blank=True, null=True)),
                ('motivo_deshabilitada', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_otra', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_obra', models.IntegerField(blank=True, null=True)),
                ('motivo_cambio_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('motivo_cambio_informante', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_obra', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_obra', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_sector_sha', models.IntegerField(blank=True, null=True)),
                ('representa_junta', models.BooleanField(blank=True, null=True)),
                ('parte_junta', models.BooleanField(blank=True, null=True)),
                ('nombre_usuario_obra', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('id_medicion1', models.IntegerField(blank=True, null=True)),
                ('id_obra_captacion', models.IntegerField(blank=True, null=True)),
                ('canal_transmision', models.IntegerField(blank=True, null=True)),
                ('tipo_medicion', models.IntegerField(blank=True, null=True)),
                ('fecha_medicion', models.DateTimeField(blank=True, null=True)),
                ('fecha_origen', models.DateTimeField(blank=True, null=True)),
                ('caudal', models.FloatField(blank=True, null=True)),
                ('altura_limnimetrica', models.FloatField(blank=True, null=True)),
                ('totalizador', models.IntegerField(blank=True, null=True)),
                ('nivel_freatico', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
